# Heuers' statistical Football model

The following implementation aims to recreate the Football model of Prof. Dr. Andreas Heuer.

In [221]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from functools import lru_cache
import warnings
from sklearn.linear_model import LinearRegression

NUM_OF_COUNTRIES = 5
NUM_OF_SEASONS = 25
NUM_OF_MATCHES = 9130
NUM_OF_MATCHES_IN_A_SEASON = 1826
SEED = 1893

np.random.seed(SEED)
warnings.filterwarnings('ignore')

In [222]:
# Helperfunctions
def score_from_amount_and_diff(amount, diff):
    if diff < 0:
        home_score = (amount + diff) / 2
        away_score = home_score - diff
    else:
        away_score = (amount - diff) / 2
        home_score = away_score + diff

    # cut excess floating numbers
    if (home_score - int(home_score)) == 0 and (away_score - int(away_score)) == 0:
        home_score = int(home_score)
        away_score = int(away_score)
    
    return home_score, away_score


def print_formatted_pred_score(country, season, matchnumber, ht_name, at_name, ht_pred_score, at_pred_score, ht_actual_score, at_actual_score):
    print("%4s %3s %3s %20s %20s %15s | %6s" %
          (country, season, matchnumber, ht_name, at_name,
           str(ht_pred_score)[0:4] + ":" + str(at_pred_score)[0:4],
           f"{ht_actual_score}:{at_actual_score}"))


def closed_form_solution(X, y):
    # alternative: np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
    return np.linalg.solve(np.dot(X.T, X), np.dot(X.T, y))

## Step 1 - Homefieldadvantage (per country and season)

In [223]:
df_homefield = pd.read_csv('data/plot_homefield_adv.csv', sep=';')
avg_homefield_adv = np.sum(df_homefield["homefield_adv"]) / NUM_OF_SEASONS
print("Average homefield advantage on all games:", avg_homefield_adv)

Average homefield advantage on all games: 0.36837358101135187

In [224]:
df_country_season_homefield_adv = pd.read_csv(
    "data/country_season_homefield_adv.csv", sep=";")

df_country_season_homefield_adv

,country,season,matchnumber,hf_adv_last_three_seasons,hf_adv_current_season,hf_adv_actual
0,ENG,14,1,0.000000,-0.300000,-0.6
1,ENG,14,2,0.000000,0.033333,0.7
2,ENG,14,3,0.000000,-0.075000,-0.4
3,ENG,14,4,0.000000,0.060000,0.6
4,ENG,14,5,0.000000,0.016667,-0.2
...,...,...,...,...,...,...
925,ITA,18,34,0.317094,0.262857,0.5
926,ITA,18,35,0.317094,0.247222,-0.3
927,ITA,18,36,0.317094,0.248649,0.3
928,ITA,18,37,0.317094,0.268421,1.0
929,ITA,18,38,0.317094,0.279487,0.7

In [243]:
@lru_cache(maxsize=None)
def h_country_season_homefield_adv(country, season, matchnumber):
    if season == 14 and matchnumber == 1:
        return avg_homefield_adv
        
    sub_df = df_country_season_homefield_adv.query(
        f"country == '{country}' and season < {season} or (country == '{country}' and season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["hf_adv_last_three_seasons",
                "hf_adv_current_season"]].values
    y = sub_df["hf_adv_actual"].values

    # w = closed_form_solution(X, y)
    model = LinearRegression(positive=True).fit(X, y)
    print("COEF | INTERCEPT",model.coef_, "|",model.intercept_)
    
    input_df = df_country_season_homefield_adv.query(
        f"country == '{country}' and season == {season} and matchnumber == {matchnumber}")
    input = input_df[["hf_adv_last_three_seasons",
                      "hf_adv_current_season"]].values

    # return np.dot(w, input.T)[0]
    return model.predict(input)[0]

print("Homefield advantage:", h_country_season_homefield_adv("ESP", 14, 4))

for i in range(1,35):
    print("MatchNo", i, h_country_season_homefield_adv("GER",18,i))

COEF | INTERCEPT [0. 0.] | 0.6333333333333334
Homefield advantage: 0.6333333333333334
COEF | INTERCEPT [0.         1.91787673] | -0.2675084626515559
MatchNo 1 0.4783324866385429
COEF | INTERCEPT [0.00676924 1.92714213] | -0.27045665422293896
MatchNo 2 -0.196545242676915
COEF | INTERCEPT [0.00201732 2.01207151] | -0.30166156125948795
MatchNo 3 0.20211201299118897
COEF | INTERCEPT [0.01535686 1.97666365] | -0.28841317020025864
MatchNo 4 0.11267228742535623
COEF | INTERCEPT [0.0134661  1.98567049] | -0.29175163313799
MatchNo 5 0.44872632655023126
COEF | INTERCEPT [0.03250258 2.00190579] | -0.29729756411660474
MatchNo 6 0.6681664735905626
COEF | INTERCEPT [0.04533252 2.03824696] | -0.31033765767401
MatchNo 7 0.697458542980971
COEF | INTERCEPT [0.0412502  2.02604957] | -0.30595623341404915
MatchNo 8 0.5849497423245711
COEF | INTERCEPT [0.02596184 1.99449971] | -0.29472261597233373
MatchNo 9 0.4241582252015279
COEF | INTERCEPT [0.00866714 1.98709603] | -0.29237460887888234
MatchNo 10 0.2728790855573979
COEF | INTERCEPT [0.         2.01072036] | -0.3028940559456877
MatchNo 11 0.3301105030269072
COEF | INTERCEPT [1.55387184e-03 2.00541058e+00] | -0.299231764093453
MatchNo 12 0.38696077482443914
COEF | INTERCEPT [0.00763559 2.00604575] | -0.29933654603602816
MatchNo 13 0.34036369171121456
COEF | INTERCEPT [6.38193181e-04 2.01001313e+00] | -0.30093667881112557
MatchNo 14 0.47352967092821513
COEF | INTERCEPT [0.02052908 2.03321028] | -0.3090143996776184
MatchNo 15 0.4611297158433371
COEF | INTERCEPT [0.0151506 2.0282064] | -0.3072948111703696
MatchNo 16 0.48049945789654636
COEF | INTERCEPT [0.01685604 2.03021607] | -0.3079949958372069
MatchNo 17 0.3875902211791159
COEF | INTERCEPT [0.         2.02996388] | -0.3083776616171587
MatchNo 18 0.2733078950381049
COEF | INTERCEPT [0.         2.06050014] | -0.3249860507225077
MatchNo 19 0.24737510063691687
COEF | INTERCEPT [0.        2.0655573] | -0.3276027055896938
MatchNo 20 0.20791215103524024
COEF | INTERCEPT [0.         2.08057225] | -0.3347984263836856
MatchNo 21 0.22212242805817417
COEF | INTERCEPT [0.        2.0712494] | -0.3301887454999909
MatchNo 22 0.25016132898877474
COEF | INTERCEPT [0.       2.060674] | -0.32463735321204584
MatchNo 23 0.2668524058057638
COEF | INTERCEPT [0.         2.05524694] | -0.3216653638369602
MatchNo 24 0.24466934983219035
COEF | INTERCEPT [0.         2.06421258] | -0.32625543896151643
MatchNo 25 0.28242262949156716
COEF | INTERCEPT [0.         2.05148057] | -0.31883563618619337
MatchNo 26 0.33122199263963037
COEF | INTERCEPT [1.75816612e-03 2.04431701e+00] | -0.31347677953026104
MatchNo 27 0.4659692659281917
COEF | INTERCEPT [0.03652555 2.08651791] | -0.32820181717979097
MatchNo 28 0.48491291780111717
COEF | INTERCEPT [0.03567396 2.08543952] | -0.3278247623577596
MatchNo 29 0.45019997239913323
COEF | INTERCEPT [0.02435425 2.07575611] | -0.3245162131998821
MatchNo 30 0.44348554353702974
COEF | INTERCEPT [0.02215543 2.07393681] | -0.32389612456582395
MatchNo 31 0.4045203178698795
COEF | INTERCEPT [0.01022505 2.07007665] | -0.322733151844344
MatchNo 32 0.45476219503014453
COEF | INTERCEPT [0.0255752  2.08609508] | -0.32827715043857764
MatchNo 33 0.43120686337401815
COEF | INTERCEPT [0.01513327 2.0791658 ] | -0.3259588339917538
MatchNo 34 0.4915748773366578

## Step 2 - Goalamount per match (per country and season)

there are higher scored countrys as well as lower scoring ones
for now the goalamount will be modeled as a constant

In [226]:
df_goalamount = pd.read_csv('data/plot_goalamount.csv', sep=';')
avg_goalamount = np.sum(df_goalamount["goalamount"]) / NUM_OF_SEASONS
print("Average goalamount of all games:", avg_goalamount)

Average goalamount of all games: 2.724046095631235

In [227]:
df_country_season_goalamount = pd.read_csv(
    "data/country_season_goalamount.csv", sep=";")

df_country_season_goalamount

,country,season,matchnumber,ga_last_three_seasons,ga_current_season,ga_actual
0,ENG,14,1,0.000000,0.000000,2.6
1,ENG,14,2,0.000000,2.600000,2.3
2,ENG,14,3,0.000000,2.450000,3.2
3,ENG,14,4,0.000000,2.700000,3.0
4,ENG,14,5,0.000000,2.775000,3.2
...,...,...,...,...,...,...
925,ITA,18,34,2.735965,2.663636,2.3
926,ITA,18,35,2.735965,2.652941,2.9
927,ITA,18,36,2.735965,2.660000,3.1
928,ITA,18,37,2.735965,2.672222,2.8
929,ITA,18,38,2.735965,2.675676,2.9

In [244]:
@lru_cache(maxsize=None)
def h_country_season_goalamount(country, season, matchnumber):
    if season == 14 and matchnumber == 1:
        return avg_goalamount
        
    sub_df = df_country_season_goalamount.query(
        f"country == '{country}' and season < {season} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["ga_last_three_seasons",
                "ga_current_season"]].values  # no bias
    y = sub_df["ga_actual"].values

    # w = closed_form_solution(X, y)
    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "-",model.intercept_)

    input_df = df_country_season_goalamount.query(
        f"country == '{country}' and season == {season} and matchnumber == {matchnumber}")
    input = input_df[["ga_last_three_seasons",
                    "ga_current_season"]].values

    # return np.dot(w, input.T)[0]
    return model.predict(input)[0]


print("Goalamount:", h_country_season_goalamount("GER", 18, 18))

Goalamount: 2.809943346321686

## Step 3: Teamstrength and expected goaldifference + Step 4: Specialty for promoters

In [229]:
df_matches = pd.read_csv('data/matches_heuer.csv', sep=';')

df_matches

,country,season,matchnumber,teamname,curr_eff_chancediff,past_chancediff_combined,curr_eff_chanceamount,past_chanceamount,curr_fitness,market_value_ln_relative,is_promoter,is_home,actual_goalamount,actual_goaldiff
0,ENG,14,1,Queens Park Rangers,0.000000,0.000000,0.000000,0.000000,0.000000,-0.392415,True,True,1,-1
1,ENG,14,1,Hull,0.000000,0.000000,0.000000,0.000000,0.000000,-0.348740,False,False,1,1
2,ENG,14,1,Newcastle,0.000000,0.000000,0.000000,0.000000,0.000000,-0.169272,False,True,2,-2
3,ENG,14,1,Man City,0.000000,0.000000,0.000000,0.000000,0.000000,1.002768,False,False,2,2
4,ENG,14,1,Burnley,0.000000,0.000000,0.000000,0.000000,0.000000,-1.140622,True,True,4,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18255,ITA,18,38,Napoli,5.242267,5.293421,3.415385,8.877193,3.375719,1.070083,False,False,5,-1
18256,ITA,18,38,Inter,2.881676,2.380263,1.042860,6.754386,1.768259,1.024225,False,True,3,1
18257,ITA,18,38,Empoli,-3.462648,-3.058772,-0.805584,4.403509,2.088522,-0.738824,True,False,3,-1
18258,ITA,18,38,Cagliari,-3.170633,-1.972368,-1.823289,4.824561,-3.719535,-0.358838,False,True,3,-1
18259,ITA,18,38,Udinese,-2.084748,-0.971053,-1.537836,5.000000,1.322783,-0.098958,False,False,3,1

In [230]:
@lru_cache(maxsize=None)
def h_teamstrength(country, season, matchnumber, teamname):
    if season == 14 and matchnumber == 1:
        return 0

    sub_df = df_matches.query(
        f"season < {season} and matchnumber == {matchnumber} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_chancediff_combined",
                "curr_eff_chancediff", "curr_fitness", "market_value_ln_relative"]].values # no bias
    y = []

    # one team is only responsible for half of the goaldiff
    for index, row in sub_df.iterrows():
        goal_diff = row["actual_goaldiff"]
        if row["is_home"]:
            goal_diff -= avg_homefield_adv # h_country_season_hf_adv
        else:
            goal_diff += avg_homefield_adv  # h_country_season_hf_adv
        y.append(goal_diff/2)

    # w = closed_form_solution(X, y)
    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "-",model.intercept_)

    input_df = df_matches.query(
        f"season == {season} and matchnumber == {matchnumber} and teamname == '{teamname}'")

    # Homefield advantage correction
    homefield_matches = df_matches.query(
        f"season == {season} and matchnumber < {matchnumber} and teamname == '{teamname}' and is_home").count()["is_home"]

    if matchnumber > 1:
        additional_homefield_matches = homefield_matches - \
            ((matchnumber - 1) - homefield_matches)
        if additional_homefield_matches > 0:
            input_df["curr_eff_chancediff"] -= (additional_homefield_matches * \
                h_country_season_homefield_adv(country, season, matchnumber) * 4) / (matchnumber - 1)

    # Step 4: Specialty for promoters
    if input_df.iloc[0]["is_promoter"]:
        input_df["past_chancediff_combined"] = input_df["past_chancediff_combined"] * \
            0.45 * model.coef_[1]
        input_df["curr_eff_chancediff"] = input_df["curr_eff_chancediff"] * 0.45 * model.coef_[1]

    input = input_df[["past_chancediff_combined",
                      "curr_eff_chancediff", "curr_fitness","market_value_ln_relative"]].values

    # teamstrength = np.dot(w, input.T)[0]
    teamstrength = model.predict(input)[0]

    if input_df.iloc[0]["is_promoter"]:
        teamstrength -= (13/34)

    return teamstrength

print("Teamstrength:", h_teamstrength("ENG", 16, 12, "Leicester"))

Teamstrength: -0.04095944011261097

## Step 5: Expected goalamount per match

In [231]:
@lru_cache(maxsize=None)
def h_goalamount_from_avg_per_match(country, season, matchnumber, teamname):
    if season == 14 and matchnumber == 1:
        return 0

    sub_df = df_matches.query(
        f"season < {season} and matchnumber == {matchnumber} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_chanceamount", "curr_eff_chanceamount"]].values 
    y = []
    for index, row in sub_df.iterrows():
        y.append(row["actual_goalamount"] - avg_goalamount) # - h_country_season_goalamount(row["country"], row["season"], row["matchnumber"]))

    # w = closed_form_solution(X, y)
    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "-",model.intercept_)

    input_df = df_matches.query(
        f"season == {season} and matchnumber == {matchnumber} and teamname == '{teamname}'")
    input = input_df[["past_chanceamount", "curr_eff_chanceamount"]].values

    # return np.dot(w, input.T)[0]
    return model.predict(input)[0]

print("Goalamount from avg:", h_goalamount_from_avg_per_match("GER", 16, 19, "Bayern"))

Goalamount from avg: 0.4361184922711733

## Step 6: Predicted Goals

In [232]:
def predicted_goals(country, season, matchnumber, hometeam, awayteam):
    goalamount = h_goalamount_from_avg_per_match(
        country, season, matchnumber, hometeam) + h_goalamount_from_avg_per_match(country, season, matchnumber, awayteam) + h_country_season_goalamount(country, season, matchnumber)
    goaldiff = h_country_season_homefield_adv(country, season, matchnumber) + h_teamstrength(country, season, matchnumber, hometeam) - h_teamstrength(country, season, matchnumber, awayteam)
    return (goalamount, goaldiff)

## Step 7: Dependence on matchnumber

In [233]:
def matchnumber_goalamount_multiplier(country, matchnumber):
    # Uncertain
    if country == 'GER':
        if matchnumber < 18:
            return 1.02
        elif matchnumber < 31:
            return 0.95
        else:
            return 1.2
    else:
        if matchnumber < 19:
            return 1.02
        elif matchnumber < 35:
            return 0.95
        else:
            return 1.2

## Final: Full run on dataset to measure goalamount and goaldifference error

In [234]:
def predict(country, season, matchnumber, hometeam, awayteam):
    amount, diff = predicted_goals(country, season, matchnumber, hometeam, awayteam)

    home_score, away_score = score_from_amount_and_diff(amount, diff)

    home_score *= matchnumber_goalamount_multiplier(country, matchnumber)
    away_score *= matchnumber_goalamount_multiplier(country, matchnumber)

    return (home_score+ away_score), (home_score - away_score)

In [235]:
# For match in Dataset run prediction and measure error
do_a_whole_run = True

if not do_a_whole_run:
    print("Skipped testing run")

test_df = df_matches.query(f"season == 18")
ga_abs_error, gd_abs_error = 0, 0

if do_a_whole_run:
    for index, row in test_df.iterrows():
        if index % 2 == 0:
            home_score, away_score = score_from_amount_and_diff(
                row["actual_goalamount"], row["actual_goaldiff"])
            hometeam = row["teamname"]
            continue
        else:
            awayteam = row["teamname"]
            ga_pred, gd_pred = predict(
                row["country"], row["season"], row["matchnumber"], hometeam, awayteam)
            ga_abs_error += np.abs(ga_pred - row["actual_goalamount"])
            gd_abs_error += np.abs(gd_pred - row["actual_goaldiff"])
            h_score_pred, a_score_pred = score_from_amount_and_diff(ga_pred,gd_pred)
            print_formatted_pred_score(row["country"], row["season"], row["matchnumber"], hometeam, awayteam, h_score_pred ,a_score_pred, home_score, away_score)

    print("Absolute error goalamount",
          ga_abs_error / NUM_OF_MATCHES_IN_A_SEASON)
    print("Absolute error goaldiff", gd_abs_error / NUM_OF_MATCHES_IN_A_SEASON)

 ENG  18   1               Wolves              Everton       1.20:1.52 |    2:2
 ENG  18   1              Watford             Brighton       1.48:1.17 |    2:0
 ENG  18   1          Southampton              Burnley       1.58:1.14 |    0:0
 ENG  18   1            Newcastle            Tottenham       1.00:1.97 |    1:2
 ENG  18   1              Man Utd            Leicester       1.74:1.14 |    2:1
 ENG  18   1              Arsenal             Man City       1.39:1.80 |    0:2
 ENG  18   1         Huddersfield              Chelsea       0.86:1.96 |    0:3
 ENG  18   1               Fulham       Crystal Palace       1.25:1.41 |    0:2
 ENG  18   1          Bournemouth              Cardiff       1.61:1.08 |    2:0
 ENG  18   1            Liverpool             West Ham       2.04:0.95 |    4:0
 ENG  18   2            Tottenham               Fulham       2.03:0.25 |    3:1
 ENG  18   2              Everton          Southampton       1.64:0.64 |    2:1
 ENG  18   2             West Ham          Bournemouth       1.56:0.71 |    1:2
 ENG  18   2             Brighton              Man Utd       1.21:1.07 |    3:2
 ENG  18   2              Burnley              Watford       1.50:0.78 |    1:3
 ENG  18   2              Cardiff            Newcastle       1.22:1.06 |    0:0
 ENG  18   2              Chelsea              Arsenal       1.66:0.62 |    3:2
 ENG  18   2             Man City         Huddersfield       2.05:0.23 |    6:1
 ENG  18   2            Leicester               Wolves       1.80:0.48 |    2:0
 ENG  18   2       Crystal Palace            Liverpool       1.21:1.07 |    0:2
 ENG  18   3               Wolves             Man City       1.18:1.85 |    1:1
 ENG  18   3              Man Utd            Tottenham       1.80:1.35 |    0:3
 ENG  18   3         Huddersfield              Cardiff       1.41:0.61 |    0:0
 ENG  18   3          Bournemouth              Everton       1.63:1.06 |    2:2
 ENG  18   3            Newcastle              Chelsea       1.34:1.45 |    1:2
 ENG  18   3              Watford       Crystal Palace       1.69:0.89 |    2:1
 ENG  18   3              Arsenal             West Ham       1.94:0.79 |    3:1
 ENG  18   3            Liverpool             Brighton       2.34:0.42 |    1:0
 ENG  18   3          Southampton            Leicester       1.57:0.95 |    1:2
 ENG  18   3               Fulham              Burnley       1.40:0.89 |    4:2
 ENG  18   4              Watford            Tottenham       1.58:2.01 |    2:1
 ENG  18   4             Man City            Newcastle       2.38:1.18 |    2:1
 ENG  18   4             West Ham               Wolves       1.78:1.05 |    0:1
 ENG  18   4       Crystal Palace          Southampton       1.63:1.38 |    0:2
 ENG  18   4              Chelsea          Bournemouth       2.21:1.21 |    2:0
 ENG  18   4              Burnley              Man Utd       1.30:1.73 |    0:2
 ENG  18   4              Everton         Huddersfield       1.90:0.93 |    1:1
 ENG  18   4              Cardiff              Arsenal       1.03:1.96 |    2:3
 ENG  18   4             Brighton               Fulham       1.76:1.25 |    2:2
 ENG  18   4            Leicester            Liverpool       1.58:1.84 |    1:2
 ENG  18   5               Wolves              Burnley       1.28:1.04 |    1:0
 ENG  18   5         Huddersfield       Crystal Palace       1.23:1.13 |    0:1
 ENG  18   5            Tottenham            Liverpool       1.65:1.33 |    1:2
 ENG  18   5            Newcastle              Arsenal       1.30:1.36 |    1:2
 ENG  18   5              Everton             West Ham       1.54:0.95 |    1:3
 ENG  18   5          Bournemouth            Leicester       1.39:1.11 |    4:2
 ENG  18   5              Watford              Man Utd       1.26:1.38 |    1:2
 ENG  18   5              Chelsea              Cardiff       2.16:0.39 |    4:1
 ENG  18   5             Man City               Fulham       2.22:0.70 |    3:0
 ENG  18   5          Southampton             Brighton       1.53:0.87 |    2:2
 ENG  18   6               Fulham              Watford       1.39:1.30 |    1:1
 ENG  18   6              Cardiff             Man City       1.05:2.08 |    0:5
 ENG  18   6            Liverpool          Southampton       2.15:1.09 |    3:0
 ENG  18   6             Brighton            Tottenham       1.34:1.70 |    1:2
 ENG  18   6             West Ham              Chelsea       1.47:1.64 |    0:0
 ENG  18   6              Man Utd               Wolves       2.04:0.79 |    1:1
 ENG  18   6              Arsenal              Everton       1.89:1.30 |    2:0
 ENG  18   6              Burnley          Bournemouth       1.45:1.23 |    4:0
 ENG  18   6            Leicester         Huddersfield       1.79:0.87 |    3:1
 ENG  18   6       Crystal Palace            Newcastle       1.59:1.09 |    0:0
 ENG  18   7             West Ham              Man Utd       1.55:1.38 |    3:1
 ENG  18   7               Wolves          Southampton       1.49:1.34 |    2:0
 ENG  18   7              Cardiff              Burnley       1.30:1.35 |    1:2
 ENG  18   7              Chelsea            Liverpool       1.90:1.37 |    1:1
 ENG  18   7              Everton               Fulham       2.04:0.83 |    3:0
 ENG  18   7             Man City             Brighton       2.27:0.89 |    2:0
 ENG  18   7              Arsenal              Watford       2.04:1.03 |    2:0
 ENG  18   7         Huddersfield            Tottenham       1.30:1.61 |    0:2
 ENG  18   7            Newcastle            Leicester       1.57:1.27 |    0:2
 ENG  18   7          Bournemouth       Crystal Palace       1.71:1.14 |    2:1
 ENG  18   8            Leicester              Everton       1.70:1.56 |    1:2
 ENG  18   8              Watford          Bournemouth       1.65:1.52 |    0:4
 ENG  18   8            Tottenham              Cardiff       2.33:0.79 |    1:0
 ENG  18   8            Liverpool             Man City       2.12:1.97 |    0:0
 ENG  18   8          Southampton              Chelsea       1.44:1.88 |    0:3
 ENG  18   8       Crystal Palace               Wolves       1.80:1.23 |    0:1
 ENG  18   8               Fulham              Arsenal       1.34:1.94 |    1:5
 ENG  18   8              Burnley         Huddersfield       1.56:1.18 |    1:1
 ENG  18   8             Brighton             West Ham       1.38:1.44 |    1:0
 ENG  18   8              Man Utd            Newcastle       1.90:1.13 |    3:2
 ENG  18   9              Cardiff               Fulham       1.12:1.34 |    4:2
 ENG  18   9              Everton       Crystal Palace       1.57:1.18 |    2:0
 ENG  18   9         Huddersfield            Liverpool       1.01:1.86 |    0:1
 ENG  18   9            Newcastle             Brighton       1.38:1.15 |    0:1
 ENG  18   9             Man City              Burnley       1.97:1.00 |    5:0
 ENG  18   9              Arsenal            Leicester       1.68:1.34 |    3:1
 ENG  18   9             West Ham            Tottenham       1.38:1.71 |    0:1
 ENG  18   9               Wolves              Watford       1.20:1.34 |    0:2
 ENG  18   9          Bournemouth          Southampton       1.44:1.32 |    0:0
 ENG  18   9              Chelsea              Man Utd       1.66:1.37 |    2:2
 ENG  18  10            Tottenham             Man City       1.67:1.81 |    0:1
 ENG  18  10       Crystal Palace              Arsenal       1.30:1.66 |    2:2
 ENG  18  10            Liverpool              Cardiff       2.16:0.71 |    4:1
 ENG  18  10               Fulham          Bournemouth       1.13:1.56 |    0:3
 ENG  18  10            Leicester             West Ham       1.45:1.32 |    1:1
 ENG  18  10          Southampton            Newcastle       1.40:1.26 |    0:0
 ENG  18  10              Watford         Huddersfield       1.42:1.12 |    3:0
 ENG  18  10              Man Utd              Everton       1.59:1.37 |    2:1
 ENG  18  10             Brighton               Wolves       1.36:1.16 |    1:0
 ENG  18  10              Burnley              Chelsea       1.03:1.83 |    0:4
 ENG  18  11             Man City          Southampton       2.07:1.06 |    6:1
 ENG  18  11             West Ham              Burnley       1.59:0.90 |    4:2
 ENG  18  11              Arsenal            Liverpool       1.67:1.54 |    1:1
 ENG  18  11              Everton             Brighton       1.72:0.87 |    3:1
 ENG  18  11               Wolves            Tottenham       1.20:1.64 |    2:3
 ENG  18  11          Bournemouth              Man Utd       1.44:1.44 |    1:2
 ENG  18  11            Newcastle              Watford       1.47:1.08 |    1:0
 ENG  18  11              Cardiff            Leicester       1.00:1.58 |    0:1
 ENG  18  11         Huddersfield               Fulham       1.46:0.92 |    1:0
 ENG  18  11              Chelsea       Crystal Palace       1.96:0.93 |    3:1
 ENG  18  12       Crystal Palace            Tottenham       1.44:1.43 |    0:1
 ENG  18  12            Leicester              Burnley       1.85:0.84 |    0:0
 ENG  18  12              Cardiff             Brighton       1.27:1.24 |    2:1
 ENG  18  12            Liverpool               Fulham       2.29:0.58 |    2:0
 ENG  18  12          Southampton              Watford       1.72:1.02 |    1:1
 ENG  18  12              Arsenal               Wolves       2.12:0.77 |    1:1
 ENG  18  12             Man City              Man Utd       2.08:1.23 |    3:1
 ENG  18  12            Newcastle          Bournemouth       1.58:1.11 |    2:1
 ENG  18  12              Chelsea              Everton       2.02:1.00 |    0:0
 ENG  18  12         Huddersfield             West Ham       1.37:1.21 |    1:1
 ENG  18  13            Tottenham              Chelsea       1.75:1.68 |    3:1
 ENG  18  13              Everton              Cardiff       2.05:0.82 |    1:0
 ENG  18  13              Burnley            Newcastle       1.41:1.33 |    1:2
 ENG  18  13               Fulham          Southampton       1.28:1.56 |    3:2
 ENG  18  13              Man Utd       Crystal Palace       1.84:1.20 |    0:0
 ENG  18  13               Wolves         Huddersfield       1.43:1.28 |    0:2
 ENG  18  13             Brighton            Leicester       1.34:1.52 |    1:1
 ENG  18  13             West Ham             Man City       1.49:1.86 |    0:4
 ENG  18  13          Bournemouth              Arsenal       1.53:1.67 |    1:2
 ENG  18  13              Watford            Liverpool       1.33:1.85 |    0:3
 ENG  18  14       Crystal Palace              Burnley       1.59:1.04 |    2:0
 ENG  18  14            Newcastle             West Ham       1.49:1.21 |    0:3
 ENG  18  14              Cardiff               Wolves       1.34:1.28 |    2:1
 ENG  18  14         Huddersfield             Brighton       1.42:1.13 |    1:2
 ENG  18  14          Southampton              Man Utd       1.49:1.48 |    2:2
 ENG  18  14            Liverpool              Everton       1.95:1.16 |    1:0
 ENG  18  14             Man City          Bournemouth       2.15:1.11 |    3:1
 ENG  18  14              Arsenal            Tottenham       1.73:1.50 |    4:2
 ENG  18  14              Chelsea               Fulham       2.15:0.77 |    2:0
 ENG  18  14            Leicester              Watford       1.73:1.10 |    2:0
 ENG  18  15               Fulham            Leicester       1.23:1.30 |    1:1
 ENG  18  15             Brighton       Crystal Palace       1.34:1.09 |    3:1
 ENG  18  15               Wolves              Chelsea       1.14:1.61 |    2:1
 ENG  18  15              Everton            Newcastle       1.66:0.94 |    1:1
 ENG  18  15              Burnley            Liverpool       1.24:1.58 |    1:3
 ENG  18  15            Tottenham          Southampton       2.00:1.05 |    3:1
 ENG  18  15              Watford             Man City       1.35:1.68 |    1:2
 ENG  18  15          Bournemouth         Huddersfield       1.61:0.86 |    2:1
 ENG  18  15              Man Utd              Arsenal       1.78:1.30 |    2:2
 ENG  18  15             West Ham              Cardiff       1.78:0.69 |    3:1
 ENG  18  16              Arsenal         Huddersfield       1.92:0.82 |    1:0
 ENG  18  16              Man Utd               Fulham       2.00:0.73 |    4:1
 ENG  18  16              Everton              Watford       1.69:0.98 |    2:2
 ENG  18  16              Cardiff          Southampton       1.10:1.46 |    1:0
 ENG  18  16              Burnley             Brighton       1.40:1.01 |    1:0
 ENG  18  16            Newcastle               Wolves       1.59:0.92 |    1:2
 ENG  18  16              Chelsea             Man City       1.81:1.49 |    2:0
 ENG  18  16          Bournemouth            Liverpool       1.36:1.59 |    0:4
 ENG  18  16             West Ham       Crystal Palace       1.55:1.09 |    3:2
 ENG  18  16            Leicester            Tottenham       1.50:1.47 |    0:2
 ENG  18  17         Huddersfield            Newcastle       1.27:1.18 |    0:1
 ENG  18  17            Tottenham              Burnley       1.90:0.87 |    1:0
 ENG  18  17       Crystal Palace            Leicester       1.41:1.25 |    1:0
 ENG  18  17               Fulham             West Ham       1.24:1.38 |    0:2
 ENG  18  17          Southampton              Arsenal       1.42:1.45 |    3:2
 ENG  18  17             Man City              Everton       1.97:1.17 |    3:1
 ENG  18  17              Watford              Cardiff       1.69:0.82 |    3:2
 ENG  18  17             Brighton              Chelsea       1.14:1.62 |    1:2
 ENG  18  17               Wolves          Bournemouth       1.29:1.34 |    2:0
 ENG  18  17            Liverpool              Man Utd       1.82:1.31 |    3:1
 ENG  18  18              Cardiff              Man Utd       0.95:1.81 |    1:5
 ENG  18  18              Chelsea            Leicester       1.79:1.16 |    0:1
 ENG  18  18             Man City       Crystal Palace       1.99:1.11 |    2:3
 ENG  18  18              Everton            Tottenham       1.41:1.58 |    2:6
 ENG  18  18             West Ham              Watford       1.50:1.21 |    0:2
 ENG  18  18              Arsenal              Burnley       1.74:1.01 |    3:1
 ENG  18  18         Huddersfield          Southampton       1.21:1.37 |    1:3
 ENG  18  18          Bournemouth             Brighton       1.47:1.09 |    2:0
 ENG  18  18            Newcastle               Fulham       1.51:1.02 |    0:0
 ENG  18  18               Wolves            Liverpool       1.08:1.88 |    0:2
 ENG  18  19            Liverpool            Newcastle       1.75:0.88 |    4:0
 ENG  18  19             Brighton              Arsenal       1.07:1.43 |    1:1
 ENG  18  19               Fulham               Wolves       1.15:1.03 |    1:1
 ENG  18  19              Man Utd         Huddersfield       1.66:0.76 |    3:1
 ENG  18  19       Crystal Palace              Cardiff       1.54:0.68 |    0:0
 ENG  18  19          Southampton             West Ham       1.31:1.15 |    1:2
 ENG  18  19            Leicester             Man City       1.27:1.58 |    2:1
 ENG  18  19              Burnley              Everton       1.07:1.24 |    1:5
 ENG  18  19            Tottenham          Bournemouth       1.71:1.02 |    5:0
 ENG  18  19              Watford              Chelsea       1.07:1.51 |    1:2
 ENG  18  20              Watford            Newcastle       1.38:1.05 |    1:1
 ENG  18  20             Brighton              Everton       1.19:1.28 |    1:0
 ENG  18  20       Crystal Palace              Chelsea       1.21:1.50 |    0:1
 ENG  18  20          Southampton             Man City       1.34:1.65 |    1:3
 ENG  18  20              Man Utd          Bournemouth       1.77:1.00 |    4:1
 ENG  18  20            Liverpool              Arsenal       1.81:1.24 |    5:1
 ENG  18  20              Burnley             West Ham       1.25:1.19 |    2:0
 ENG  18  20            Leicester              Cardiff       1.74:0.71 |    0:1
 ENG  18  20            Tottenham               Wolves       1.98:0.80 |    1:3
 ENG  18  20               Fulham         Huddersfield       1.29:1.04 |    1:0
 ENG  18  21              Chelsea          Southampton       1.71:1.04 |    0:0
 ENG  18  21             Man City            Liverpool       1.68:1.52 |    2:1
 ENG  18  21             West Ham             Brighton       1.42:1.06 |    2:2
 ENG  18  21            Newcastle              Man Utd       1.15:1.53 |    0:2
 ENG  18  21          Bournemouth              Watford       1.38:1.17 |    3:3
 ENG  18  21         Huddersfield              Burnley       1.17:1.16 |    1:2
 ENG  18  21               Wolves       Crystal Palace       1.15:1.34 |    0:2
 ENG  18  21              Arsenal               Fulham       1.74:0.89 |    4:1
 ENG  18  21              Everton            Leicester       1.40:1.22 |    0:1
 ENG  18  21              Cardiff            Tottenham       0.82:1.84 |    0:3
 ENG  18  22              Burnley               Fulham       1.39:1.04 |    2:1
 ENG  18  22              Chelsea            Newcastle       1.76:0.94 |    2:1
 ENG  18  22              Cardiff         Huddersfield       1.08:1.28 |    0:0
 ENG  18  22              Everton          Bournemouth       1.52:1.16 |    2:0
 ENG  18  22            Leicester          Southampton       1.48:1.19 |    1:2
 ENG  18  22       Crystal Palace              Watford       1.39:1.17 |    1:2
 ENG  18  22             West Ham              Arsenal       1.36:1.49 |    1:0
 ENG  18  22             Man City               Wolves       2.05:0.91 |    3:0
 ENG  18  22            Tottenham              Man Utd       1.67:1.45 |    0:1
 ENG  18  22             Brighton            Liverpool       1.08:1.75 |    0:1
 ENG  18  23          Southampton              Everton       1.28:1.26 |    2:1
 ENG  18  23            Newcastle              Cardiff       1.46:0.73 |    3:0
 ENG  18  23              Watford              Burnley       1.30:0.99 |    0:0
 ENG  18  23              Man Utd             Brighton       1.66:0.87 |    2:1
 ENG  18  23            Liverpool       Crystal Palace       1.80:0.98 |    4:3
 ENG  18  23              Arsenal              Chelsea       1.45:1.49 |    2:0
 ENG  18  23          Bournemouth             West Ham       1.33:1.17 |    2:0
 ENG  18  23         Huddersfield             Man City       0.98:1.76 |    0:3
 ENG  18  23               Wolves            Leicester       1.05:1.34 |    4:3
 ENG  18  23               Fulham            Tottenham       1.00:1.69 |    1:2
 ENG  18  24            Tottenham              Watford       1.87:0.90 |    2:1
 ENG  18  24            Newcastle             Man City       1.21:1.58 |    2:1
 ENG  18  24            Liverpool            Leicester       1.87:1.00 |    1:1
 ENG  18  24              Arsenal              Cardiff       1.96:0.60 |    2:1
 ENG  18  24              Man Utd              Burnley       1.77:0.77 |    2:2
 ENG  18  24               Wolves             West Ham       1.21:1.18 |    3:0
 ENG  18  24          Bournemouth              Chelsea       1.27:1.43 |    4:0
 ENG  18  24          Southampton       Crystal Palace       1.45:1.02 |    1:1
 ENG  18  24         Huddersfield              Everton       1.12:1.23 |    0:1
 ENG  18  24               Fulham             Brighton       1.21:1.01 |    4:2
 ENG  18  25              Chelsea         Huddersfield       1.92:0.60 |    5:0
 ENG  18  25       Crystal Palace               Fulham       1.59:0.74 |    2:0
 ENG  18  25              Everton               Wolves       1.70:0.71 |    1:3
 ENG  18  25            Tottenham            Newcastle       1.89:0.83 |    1:0
 ENG  18  25              Cardiff          Bournemouth       1.10:1.25 |    2:0
 ENG  18  25              Burnley          Southampton       1.33:1.06 |    1:1
 ENG  18  25             Brighton              Watford       1.33:0.96 |    0:0
 ENG  18  25             West Ham            Liverpool       1.35:1.44 |    1:1
 ENG  18  25             Man City              Arsenal       1.94:1.14 |    3:1
 ENG  18  25            Leicester              Man Utd       1.44:1.23 |    0:1